### ISSUE TITLE
Provide reference implementation for "Must have" guidelines

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/practical-api-guidelines#10]
Provide reference implementation for "Must have" guidelines that illustrates how this can be achieved.

- Result should end up in `/maturity-level-one/src`
- Should be written in .NET Core
- Should provide documentation on how things are implemented

**Comment by MassimoC** [comment]
still few things to be completed. target date : 28 Jan

**Comment by MassimoC** [comment]
Must have guideline + practical implementation is completed.
