### ISSUE TITLE
Do not respond with BadRequest when the request is perfectly fine but the operation is not allowed / possible

### ISSUE THREAD

**Issue by MassimoC** [CoditEU/practical-api-guidelines#100]
This should not result in a BadRequest response.

A BadRequest indicates that something is wrong at the client-level; something is wrong with the request object.  This is not the case when you have no inventory left.
A NotAllowed statuscode might be more appropriate although I'm not convinced of it either.

This issue is related to this code
```csharp
var customization = await _coditoRepository.GetCustomizationAsync(id);
if (customization == null)
{
    return NotFound(new ProblemDetailsError(StatusCodes.Status404NotFound));
}
if (customization.InventoryLevel <= 0)
{
    return BadRequest();
}
```

_Originally posted by @fgheysels

**Comment by MassimoC** [comment]
on v1/CustomizationController.cs
```csharp
            if (customization.InventoryLevel <= 0)
            {
                return BadRequest();
            }
```

**Comment by MassimoC** [comment]
405 "Method Not Allowed" to be used when a HTTP method is not allowed for a specific resource
Few alternatives to 400:
- 409 Conflict. The request cannot be processed because there is a conflict with the current state of the resource.
- 404 NotFound. The resource (in this case out of stock) is not there anymore but it might be available in the future

**Comment by fgheysels** [comment]
I think that, for the case where you cannot sell a car because there is no inventory, a 409 statuscode would be appropriate
