### ISSUE TITLE
Migrate CI to Azure DevOps

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/practical-api-guidelines#108]
Now that Azure DevOps has public builds I'm curious if we should move to that instead over using Travis CI given we're more used to it and will be easier to onboard new folks.

Thoughts?

**Comment by tomkerkhove** [comment]
It's not a must, I'm just curious.

**Comment by fgheysels** [comment]
I think it's a good idea to move to Azure Devops

**Comment by tomkerkhove** [comment]
I can pick this up if you guys are up for it.

@MassimoC 	I'd need to have a project to build them on and a connection towards GitHub.

**Comment by tomkerkhove** [comment]
Would YAML configuration be ok?

**Comment by MassimoC** [comment]
Go for YAML. I think is the best approach for OSS

**Comment by tomkerkhove** [comment]
This is done, but it only builds as debug - Otherwise we were having issues with SQL connection.

Can you have a look at this please @fgheysels 	?

**Comment by tomkerkhove** [comment]
Build cleaned up via #119.

Remaining things open before closure:
- [ ] Building in debug is required due to config for SQL (see above, hope @fgheysels 	has something for this)
- [ ] Fix lack of automatic PR trigger
- [ ] Remove travis CI

With respect to build config, we used to build in debug for travis as well. Do we need release build or not? I think it's good practice but no expert

**Comment by tomkerkhove** [comment]
You can manually trigger CI for now via `/azp run ci`

**Comment by tomkerkhove** [comment]
Completed ✔️
