### ISSUE TITLE
Align operationIds with guidelines

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/practical-api-guidelines#30]
Currently we have operationIds such as `get-all-players` which is not in line with [our guidelines](https://github.com/CoditEU/practical-api-guidelines/blob/master/maturity-level-one/README.md#defining-operationids).

This should be aligned.

**Comment by MisterKite** [comment]
I will have a look at this

**Comment by tomkerkhove** [comment]
I'm going to pick this up tomorrow so that we can merge #41 	in.

**Comment by tomkerkhove** [comment]
Have to work on other priorities so re-assigning this to Sander.

**Comment by MassimoC** [comment]
@tomkerkhove  Is this issue the same as #51  ?

**Comment by tomkerkhove** [comment]
No, thus is about operationId
