### ISSUE TITLE
Change the data model to Codito Cars

### ISSUE THREAD

**Issue by MassimoC** [CoditEU/practical-api-guidelines#79]
From world-cup to codito.

**Comment by tomkerkhove** [comment]
Would be good to provide more context as not everybody knows Codito or what it is :)

**Comment by MassimoC** [comment]
Codito Cars is a ficticious car manufacturer. Codito Cars is undergoing a digital transformation, to get its IT landscape ready for the next decade. Codit plays a vital role in this journey and implements critical parts of the backbone: Integration, APIs, IoT and Azure PaaS solutions.

All development is done according to the best practices and guidelines, applicable at Codit. 
Codito-Cloud is a cloud-native solution with a big focus on security, reliability, devops and monitoring.

**GOAL** :  Move this sample to the "Car domain" therefore it will be possible to deploy this api as part of the Codito-Cloud demo

**Comment by MassimoC** [comment]
A first migration to the codito data model has been done. Different issues have been created to manage the enhancements
